# example of configuration with docker-compose

version: '2'
services:
    polypus:
        image: polypus
        ports:
            - 4000:4000
        volumes:
            - /c/polypus/logs/:/opt/polypus/logs/:rw
            - /c/polypus/polypus.yml:/etc/polypus/polypus.yml:rw