swagger: "2.0"
info:
  version: "0.1.0"
  title: DataSourceAPI
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /api
# 
schemes:
  # tip: remove http to make production-grade
  - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
          minLength: 3
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
  /swagger:
    x-swagger-pipe: swagger_raw
    
    
  /datasources:
    # x-swagger-router-controller: datasources
    get:
      description: Return all `DataSource`
      # operationId: getAll
      responses:
        200: 
          description: Success
          schema: 
            $ref: "#/definitions/DataSource"
    post:
      description: Create new entity
      parameters:
        - name: DataSource
          in: body
          required: true
          schema:
            $ref: "#/definitions/DataSource"
          
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/DataSource"
  
  /datasources/count:
    get:
      description: Count how many entities are in db.
      responses: 
        200:
          description: Success
          schema:
            $ref: "#/definitions/CountSchema"
            
  /datasources/{_id}:
    get:
      description: Get one entity
      parameters:
        - name: _id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/DataSource"
      

x-swagger-mongoose:
  schema-options:
    timestamps: true
    
# complex objects have schema definitions
definitions:
  CountSchema:
    properties:
      count:
        type: integer
        
  DataSource:
    required:
      - name
      - adapter
    properties:
      name:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      adapter:
        type: string
